### ISSUE TITLE
Mode "economy" in settings/generaldata.ini breaks the front

### ISSUE THREAD

**Issue by MartinBelthle** [AntaresSimulatorTeam/AntaREST#1534] opened 2023-05-24 15:43 UTC
## Description

There is a section [general] in the file settings/generaldata.ini 
See below an example: 
![bug_economy](https://github.com/AntaresSimulatorTeam/AntaREST/assets/102529366/2c0a08d6-f62e-4178-a5b2-b10a032ec273)

When the value mode is different than "Economy", it breaks the front-end (view Configuration/General). But it shouldn't as a lot of studies built with AntaresSimulator have the parameter written "economy".

## Solution:

The string validation in the form should allow both writings.

**Comment by laurent-laporte-pro** [comment] 2023-06-22 09:54
duplicate of #1609 (fixed by #1610)

**Closed as completed by laurent-laporte-pro** 2023-06-22 09:54 UTC
Labels: bug, duplicate, front-end
