### ISSUE TITLE
It should be possible to modify a matrix that is empty

### ISSUE THREAD

**Issue by MartinBelthle** [AntaresSimulatorTeam/AntaREST#1529] opened 2023-05-22 12:26 UTC
## Problem Statement

When an area is created with AntaresSimulator, its load matrix is by default empty. When you want to modify a value inside it, first the application creates the default matrix and then it modifies the value.
A study created by AntaresWeb has the default matrix by default so it is never empty and this issue does not occur.
But, when a study is created with AntaresSimulator and then imported on AntaresWeb, when the user tries to modify a matrix which is empty, an error occurs, it is not possible to modify it.

## Proposed Solution

AntaresWeb should do the same thing as AntaresSimulator which is : 
1. If the matrix is empty, create its default value
2. Modify the value the user wanted

## Developer Notes

This is not an issue on the long run as the use of AntaresSimulator will disappear with time.
This feature request is valid for every matrix not only the load one.

**Comment by laurent-laporte-pro** [comment] 2023-06-08 10:04
The solution is to avoid displaying a matrix with zeros when the matrix is actually empty. The user can import a matrix with the "Import" button. In the other hand, if the user uses the Swagger API, an error should be reported.

The HTTP status 422 Unprocessable Entity be suitable in this case. The 422 error code indicates that the request is well-formed, but the server cannot process it due to invalid parameters.

**Comment by laurent-laporte-pro** [comment] 2023-06-08 10:06
duplicate of #1571

**Closed as completed by laurent-laporte-pro** 2023-06-08 10:06 UTC
Labels: feature request
