### ISSUE TITLE
[ANT-651] Use simulator v8.5 as default

### ISSUE THREAD

**Issue by makdeuneuv** [AntaresSimulatorTeam/AntaREST#1285] opened 2023-02-02 09:33 UTC
Do this issue according to the release date of simulator 8.5.0

![create_study](https://user-images.githubusercontent.com/43534797/222276802-4e56d1bd-44b8-4d3b-b32b-1dbe2d39644b.png)

**Comment by laurent-laporte-pro** [comment] 2023-03-01 15:51
~Duplicate of feat(storage): add v8.5 template (#1328)~

**Comment by laurent-laporte-pro** [comment] 2023-03-02 11:08
Corrigé dans #1328 

![Image](https://user-images.githubusercontent.com/43534797/222411776-93ecd22c-2352-4b66-aaf3-6af96ac5f0f9.png)

**Closed as completed** 2023-06-02 09:10 UTC
Labels: enhancement, front-end, hot
